### ISSUE TITLE
SSE 4 Support

### ISSUE THREAD

**Issue by ericp1337** [Blitznote/docker-ubuntu-debootstrap#1]
Is there a way to workaround the SSE 4 support requirement because my processor supports SSE4a, but throws the error listed in the README when trying to do https.

**Comment by mark-kubacki** [comment]
What pre–Gulf-War-III cpu do you have?

**Comment by ericp1337** [comment]
AMD Phenom(tm) II X6 1055T Processor × 6

**Comment by mark-kubacki** [comment]
I am sorry, but I don't see any instruction sets on this CPU class (family `10h`, »K10«) that could substitute SSE4.1.

Even if you don't use _https_ you will run into the error, because other binaries use SSE4, too. It's just a matter of time until a function that needs this is called.

[SSE4.1 and SSE4.2](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#techs=SSE4_1,SSE4_2) are supported by Intel CPUs from 2007 and later, and [AMD CPUs beginning with](http://www.cpu-world.com/Glossary/S/SSE4.html) family `15h` (»FX…«) from 2011 and later; and even VIA Nano (2008) as well as the tiny [Intel Edison](http://www.anandtech.com/show/8511/idf-2014-intel-edison-development-platform-now-shipping) have it.

No data center I work with offers that old technology without SSE4 to the public. (Except perhaps _Hetzner_, who will rent you exceptionally old stuff.)

The binaries in this Docker image use AVX2 where available, then fallback to AVX, and finally SSE4. These _instruction sets_ result in a performance increase of one order of magnitude in case of AVX2 vs bare x86_64 with TLS; and 2×–3× for something like string operations.

**Comment by ericp1337** [comment]
Oh well, thought I'd ask and see if there was a way and yeah, my desktop is super old since I built it 6 years ago.
