### ISSUE TITLE
glibc: backport patches for <math.h> isinf from 2.27

### ISSUE THREAD

**Issue by pranas** [Blitznote/docker-ubuntu-debootstrap#12]
First of all, thanks for a great project. It would be a great choice when one cannot use Alpine (likely because of muslc).

I tried switching one of my ubuntu:16.04 based images and found a problem. Eigen (and likely other math libs) does not compile with glibc version supplied. The same problem seems to have been discussed [here](https://github.com/voidlinux/void-packages/issues/7324). People blame a regression in glibc 2.26 (the version used on the latest releases).

I read the README and understand that latest version of glibc was chosen to benefit security but would it be possible to provide 2 versions, one being compatible with Ubuntu glibc? I assume this process is automated, no?

**Comment by mark-kubacki** [comment]
Compiling and running are two things. You could use a different Docker image for compiling and pass the result to this one.

I've briefly skimmed through the issue you've referenced above, and I believe it's about **libstdc++**(which comes with gcc; 7.2.0 as of today) that causes the incompatibility, not *glibc*, if at all.

In any case, you can always switch to Ubuntu's (or Debian's) package, like this (replace `gcc-7` with `gcc-6` or whatever major version it is that works for you):
```bash
. /etc/os-release
apt-get -s --allow-downgrades install \
  gcc-7-base/${UBUNTU_CODENAME} \
     libgcc1/${UBUNTU_CODENAME} \
  libstdc++6/${UBUNTU_CODENAME}
```
… because I will almost always use the latest stable *libstdc++* and *glibc* versions. *Almost* means, if they don't break any rollout of mine or my clients'.

This is how *multi-stage* builds work with Docker ≥v17.05, though I don't use them for various reasons and employ a CI system instead.
```Docker
FROM other-image-with-compatible-libstdcxx
RUN …

FROM blitznote/baseimage
RUN apt-get -q update \
 && …
COPY --from=0 /artifact.zip .
RUN unzip artifact.zip && rm artifact.zip \
 && …
```

**Comment by pranas** [comment]
Thanks for quick reply and a reminder about multi-stage builds. It would certainly work in my case.

There are various workarounds suggested in the thread I mentioned but it seems to point to glibc issue [here](https://sourceware.org/bugzilla/show_bug.cgi?id=21930).

**Comment by mark-kubacki** [comment]
Thanks for the follow up!

I will backport the patches to 2.26. A new revision of these images will be released due to a CVE today or Wed (worst case) anyway.

**Comment by mark-kubacki** [comment]
Done. Thanks!

**Comment by pranas** [comment]
Great. What's your policy on Docker hub releases?

**Comment by mark-kubacki** [comment]
Releases (any):

- As soon as possible after a vulnerability is made public that can potentially be exploited by users of Docker images (that is, not the author).
- If a vulnerability is not public, but I know it, then images will be released as soon as any dependencies hit major patch version increases. In other words, I »collect« changes and then release everything in one go. (Example: Non-public vuln in *glibc* but a new *curl* release is due in 2 days → a new Docker image 2 days later.)
- Else, every two months, usually after *curl*. (Within 48hrs in the past.)

It follows (all in consecutive order):

- »Internal« images are built automatically, using package [artifacts] from CI.
- Integration tests with these images and derivatives.
- Clients get the internal images. Back to step 1 if sth. breaks.
- Packages meant for internal consumption are uploaded
- … and their to-be-published versions built.
- Those *artifacts* are uploaded to »staging«. (Including those this issue is about:)  
https://s.blitznote.com/debs/ubuntu/amd64/staging/
- Images are rebuilt for public consumption, and pushed to the Docker hub. (Usually a day later, like today.)
- Immediately after the images, any relevant packages are moved from »staging« to »all«, »dynamic«, and so on.
- A day after that come public images for *rkt* and *blitznote/baseimage*.

… after which I mail all new patches to *upstream*, that is open-source software used in any of the images. Or upload them to whatever bugtracker is used. (But not if old revisions can be integrated with trivial changes, like patches to *openssl*, *Go*, *curl*, *bash*, *luasec*, *PHP* …; it's the responsibility of *upstream* to take care of their bugtrackers and any migrations and conversions.)

**Comment by mark-kubacki** [comment]
Some packages have two flavours, an internal one and a public one.

You can spot internal ones easily as they will throw an »kernel too old« error message with anything older than 4.13.0, currently. And usually have features and functions stripped. For example, *gcc* doesn't use its own memory allocator, *glibc* doesn't have `rand()` and some more funcs but has facilities for connections with more parameters (the modified kernel passes any discovered MTU directly, without an additional syscall, for a better TTFB), *openssl* never had *heartbeats*, *bash* has no `eval`.
They are not uploaded into `debs/ubuntu/*` unless manually by mistake.

Public ones are rebased on Ubuntu's (see their `changelog` file), any aforementioned removals are suppressed, and patches applied.

In any case, I am not paid by the public, and therefore no guarantees as to timelines or compatibility. You're welcome to use the packages and images; they will remain supported as variants of any I need for paying customers.

I hope this covers your question. If not, feel free to get in touch with me by email or phone.

**Comment by mark-kubacki** [comment]
(A bug in *apt* 1.5.1 is currently blocking the release. You might want to pull *glibc* from *staging* in the meanwhile.)

**Comment by mark-kubacki** [comment]
This has been shipped, closed and resolved long ago. For my notes:

- The backported patch has been made part of version 2.26.1
- … which has not been released
- … and version 2.27 is due in two weeks instead.

Despite this 2.26.1 will be rolled out today in my images in the next 24hrs. Indeed, it's already *staging*, albeit as 2.26-41bn (or later).
