### ISSUE TITLE
"kernel too old" error

### ISSUE THREAD

**Issue by lbogdan** [Blitznote/docker-ubuntu-debootstrap#14]
Just pulled the latest `blitznote/debootstrap-amd64:16.04` and got this when I tried to run it:
```
$ docker run --rm -it blitznote/debootstrap-amd64:16.04
FATAL: kernel too old
```
My kernel version is:
```
$ uname -a
Linux vps64831 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

LE: From what I understand, this error is caused by a `libc` compiled with `--enable-kernel=version`, when the running kernel version is lower than the one specified at compile time.

**Comment by mark-kubacki** [comment]
This has changed a few days ago and caught you by surprise. Apologies for that.

I am using features of kernel 3.18, and the next best LTS kernel version line going from that is 4.4.x. Of which 4.4.100 is the first version with mitigations for **meltdown**. Given that it will be inconvenient for a majority of users and me to get my hands on something earlier soon, I've set this as minimum.

----
Seeing that you use *Ubuntu*: Ubuntu knows *hardware enablement* and *LTS enablement stacks*. 16.04 is on Linux 4.10 (4.13 since this month).  
https://wiki.ubuntu.com/Kernel/LTSEnablementStack

I don't think I've ever supported 14.04, and if so unintentionally. In any case, there's the "kernel-ppa" with more recent kernels:  
http://kernel.ubuntu.com/~kernel-ppa/mainline/
