### ISSUE TITLE
Question: docker-ubuntu-debootstrap VS phusion/baseimage-docker

### ISSUE THREAD

**Issue by pascalandy** [Blitznote/docker-ubuntu-debootstrap#3]
Hi,

I'm curious to know if you see some advantage to your docker-ubuntu-debootstrap VS https://github.com/phusion/baseimage-docker?

Thanks!

**Comment by mark-kubacki** [comment]
I know aforementioned image, but I don't use it. The notion that a Docker base image per se has memory requirements is misleading.

I **don't** recommend most of the things mentioned there. Instead:
1. Instead of SSH use `docker exec -ti [name] /bin/bash` to enter a container, if you must.
2. Subject `/var/log` to central logging, from outside of the container.  
   For example, _systemd_ is able to fetch logs from _child-systemds_.  
   But, even better for small installations: Log to files, or `stdout` and have Docker do its thing.
3. If you need _OpenSSH_, _cron_, or other tools – install them yourself. **A base image should be kept small.**
4. `apt-get -y upgrade` is a bad practice in any Dockerfile. The base image should be updated if need be (frequency decreases if (3) is observed) and any `apt-get install` will pull updated packages by default.
5. Avoid bloat! Do only ship what in a majority of usage scenarios
   - … is needed to run binaries. (libc, libstdc++, libz)
   - … is required to install packages from upstream in a secure manner. (apt, apt-transport-https, gpg)
   - … is required to fetch, extract, and install remote packages. (curl, decompressor, shell)
   - … cannot be removed without significantly decreasing utility. (jq, tzdata)
   - … cannot be removed because it is a dependency.

Other than that please compare sizes, package lists, and versions. And known security vulnerabilities in those packages!

---

Feel free to browse through [my repositories](https://github.com/wmark) for `Dockerfile` examples. I write them in a way – where possible – which does not require any user/operator interaction in case of updates. For example, this one always gets the latest version of `syncthing/syncthing` from Github using _curl_ and _jq_:
https://github.com/wmark/docker-syncthing/blob/94ac155cbcb1079ed5e3c73f342fda1739c36191/Dockerfile#L12-L18

**Comment by mark-kubacki** [comment]
In addition to (4):

![dockerhub-chained-build](https://cloud.githubusercontent.com/assets/191736/19897907/42932f0e-a05a-11e6-9512-29acfe1f1a6a.png)

**Comment by pascalandy** [comment]
Thanks for your time on this! I'll keep this in mind :)

**Comment by mark-kubacki** [comment]
You're welcome! That's been generally speaking in an attempt to convey the design principles.

If you have any other questions, for example regarding choice of packages, then please open a separate ticket. If you find any files that shouldn't be shipped with this image (it's currently about 2000 in total), I would gladly accept that as bug. I'd always love to learn _if and how_ you use this base image, ping [me on Twitter](https://twitter.com/murmosh)!
